In [47]:
import numpy as np
import random
random.seed(0)

In [35]:
"""
First we have 3 sensors, or 3 pieces of input data.
We have 3 weights which represent the connections from the previous sensors to the current neuron.
And finally we have the bias of the current neuron.
"""
inputs = [1, 2, 3, 2.5] # sensor / input to the neuron
weights = [0.2, 0.8, -0.5, 1.0] # weight / represents relationship between previous neuron and current neuron
bias = 2 # bias / current neuron unique bias / similar to y intercept

# Output to this function is very similar to y = mx + b
# OR: y_pred = b0 + b1 * x1 + b2 * x2 + ... + bn * xn
output = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias
print(output)

2.3


In [36]:
"""
Now we are working within a "layer" because we have 3 biases which represent the 3 different neurons in our
current layer.
We also have a new dimension of weights which represent the connections between the previous layer, and our
current layer of neurons.
Finally, we still have 3 sensors of input information.
"""
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, 0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

# Now we need to do some matrix multiplication in order to find the dot product of this equation.
# We are also going to have 3 different outputs because we have 3 neurons in this layer.

# Same process as before, sum the input*weight values of the neurons in the later before it.
# Between neurons in the current layer, the weights will change, but the input values will not.

# Neuron 1
output1 = inputs[0] * weights[0][0] + \
          inputs[1] * weights[0][1] + \
          inputs[2] * weights[0][2] + \
          inputs[3] * weights[0][3] + biases[0]

output2 = inputs[0] * weights[1][0] + \
          inputs[1] * weights[1][1] + \
          inputs[2] * weights[1][2] + \
          inputs[3] * weights[1][3] + biases[1]

output3 = inputs[0] * weights[2][0] + \
          inputs[1] * weights[2][1] + \
          inputs[2] * weights[2][2] + \
          inputs[3] * weights[2][3] + biases[2]

# To demonstrate matrix multiplication much faster with numpy
o = np.dot(weights, inputs) + biases

# Output
print(output1)
print(output2)
print(output3)
print(o)

4.8
1.21
3.465
[4.8   1.21  3.465]


In [42]:
"""
Now lets keep 3 neurons in our current layer, but let's turn our sensors into a vector instead
of a scalar integer.
"""
inputs = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

# Use numpy to go faster

# First we need to transpose weights
weights = np.array(weights).T
o = np.dot(inputs, weights) + biases
print(o)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [68]:
"""
Let's turn our layer into an object to make things more simple.

A layer gets initialized with 2 important inputs:

1. The number of inputs / neurons connected to this layer
   It is important to remember that if you're getting inputs from another layer,
   it must match the number of neurons in that previous layer.
   
2. The number of neurons in this layer
   You can put as many neurons as you want in this layer.

"""
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.3 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
    
layer1 = Layer_Dense(4, 4)
layer1.forward(inputs)
print(layer1.output)

[[-0.18399827 -1.99024851  0.69354262 -0.09421036]
 [-2.5994556  -0.74798696  2.53502616  0.19123692]
 [ 0.5150805  -0.50874134 -0.19974177 -1.14060241]]
